//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionCommande
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Commande()
        {
            this.isPaid = false;
            this.statut = "Demandé";
            this.DetailsCmd = new HashSet<DetailsCmd>();
        }
    
        public int IdCmd { get; set; }
        public System.DateTime dateCmd { get; set; }
        public double totalCmd { get; set; }
        public bool isPaid { get; set; }
        public string adresseLiv { get; set; }
        public string statut { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> LivraisonId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Paiement Paiement { get; set; }
        public virtual Livraison Livraison { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailsCmd> DetailsCmd { get; set; }
    }
}
